name: build

on: [push, pull_request]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps: 

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4

      - name: install dependencies
        run: |
          pip install flake8 black

      - name: lint with flake8
        run: |
          flake8

      - name: lint with black
        run: |
          black --check .

  type-check:

    needs: lint

    runs-on: ubuntu-latest

    steps: 

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install package
        run: |
          pip install -r requirements.txt
          pip install mypy

      - name: run mypy check
        run: |
          mypy src

  doc:

    needs: type-check

    runs-on: ubuntu-latest

    steps: 

      - name: get repo
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: install package
        run: |
          pip install .[doc]

      - name: build document
        run: |
          cd doc
          make html SPHINXOPTS="-W --keep-going"
