name: build

on: [push, pull_request]

jobs:

  lint:

    runs-on: ubuntu-latest

    steps: 

      - name: get repo
        uses: actions/checkout@v2

      - name: set up Python
        uses: actions/setup-python@v2

      - name: install dependencies
        run: |
          pip install flake8 black

      - name: lint with flake8
        run: |
          flake8

      - name: lint with black
        run: |
          black --check .

  type-check:

    needs: lint

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        qt: [PySide6, PyQt6]

    steps: 

      - name: get repo
        uses: actions/checkout@v2

      - name: set up Python
        uses: actions/setup-python@v2

      - name: install qt
        run: |
          pip install ${{ matrix.qt }}

      - name: install package
        run: |
          pip install mypy .[test]

      - name: run mypy check
        run: |
          mypy civiq6
          mypy doc/source --exclude doc/source/examples
          mypy doc/source/examples/${{ matrix.qt }}

  doc:

    needs: type-check

    runs-on: ubuntu-latest

    steps: 

      - name: get repo
        uses: actions/checkout@v2

      - name: set up Python
        uses: actions/setup-python@v2

      - name: install package
        run: |
          pip install .[doc]

      - name: build document
        run: |
          cd doc
          make html SPHINXOPTS="-W --keep-going"
